### ISSUE TITLE
Error on slushfile.js Cannot read property name of undefined

### ISSUE THREAD

**Issue by busturdust** [rjrudin/slush-marklogic-spring-boot#47]
Hi All,

I am trying to get up and running with this framework. I am running on a linux machine right now.

At the step that i am supposed to run the slush command, it is failing with a `cannot read property 'name' of undefined`

I am not sure how to fix this or why it is happening. 

Error Message : 

```
/opt $ cd nbcu-ml-spring-boot/ && slush marklogic-spring-boot
/usr/local/lib/node_modules/slush-marklogic-spring-boot/slushfile.js:50
        authorName: user.name || '',
                        ^

TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/slush-marklogic-spring-boot/slushfile.js:50:25
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-marklogic-spring-boot/slushfile.js:53:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)

```

**Comment by kghmanuel** [comment]
Do try installing release/v1.0.0-alpha branch.
